"$schema" = 'https://starship.rs/config-schema.json'

format = '''
$directory$git_branch$rust$python
$character'''

palette = 'colors'

[palettes.colors]
color1 = '#b2d400'
color2 = '#ffffff'
color3 = '#464839'
color4 = '#eeefda'
color5 = '#ffffff'
color6 = '#dadcc7'
color7 = '#fafbe5'
color8 = '#546500'
color9 = '#40683f'

# Prompt symbols 
[character]
success_symbol = "[ ](color9 bold)"
error_symbol = "[ ](@{error})"
vicmd_symbol = "[](#f9e2af)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
