background-color='#101510'
osd-back-color='#b7ccb7'
osd-border-color='#233425'
osd-color='#dfe4dc'
osd-shadow-color='#1e1e2e'

#Profile which sets some quality settings (Recommended)
profile=high-quality

border = no # Optional, but recommended

#Always open the video player in full screen
#fullscreen=yes

#Don't close the player after finishing the video
keep-open=yes

# uses max quality for HLS streams
hls-bitrate=max

#The last position of your video is saved when quitting mpv
save-position-on-quit=yes

autofit-larger=50%x50%

#Force seeking (if seeking doesn't work)
force-seekable=yes

#Cursor hide in ms
cursor-autohide=100

#Audio language priority
alang=en,eng,ja,jp,jpn,de,deu,ger

#Subtitle language priority
slang=en,eng,de,deu,ger

#Video output driver
#See: https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU
vo=gpu-next

#Called API
#Use "opengl" or "d3d11" (Windows only) if you have compatibility issues. 
# gpu-api=vulkan

#Hardware decoding for whatever your CPU/GPU supports (e.g. 8bit h264 / 10bit h265)
#Use "auto-safe" or "auto-copy-safe"
#"Copy" methods are safer to use, but the performance difference is probably not as high and maybe not even worth over "no" (disabled).
#Manual options:
#Nvidia GPU: "nvdec"/"nvdec-copy" (Recommended)
#Windows: "dxva2-copy" or "vulkan"/"vulkan-copy"
#Linux: "vaapi"/"vaapi-copy" or "vulkan"/"vulkan-copy"
#Else "no" and disable it
hwdec=nvdec

#Max volume of the player
volume-max=200

osd-font='JetBrainsMono Nerd Font'
