[colors.primary]
background = '#111318'
foreground = '#e2e2e9'
 
[colors.cursor]
text = '#e2e2e9'
cursor = '#c4c6cf' 
 
[colors.vi_mode_cursor]
text = '#111318'
cursor = '#a9c7ff' 
 
[colors.search.matches]
foreground = '#44474e' 
background = '#dcbce1' 
 
[colors.search.focused_match]
foreground = '#44474e' 
background = '#a9c7ff' 
 
[colors.footer_bar]
foreground = '#44474e' 
background = '#e2e2e9' 
 
[colors.hints.start]
foreground = '#44474e' 
background = '#bdc7dc' 
 
[colors.hints.end]
foreground = '#44474e' 
background = '#bdc7dc' 
 
[colors.selection]
text = '#111318'
background = '#a9c7ff'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#a9c7ff' 
yellow = '#405f90' 
blue = '#a9c7ff' 
magenta = '#dcbce1' 
cyan = '#bdc7dc' 
white = '#FFFFFF' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
