#!/bin/sh
while read -r file
do
    case "$1" in
        "w")
            # wal -i "$file" && xrdb -merge ~/.Xresources
            # feh --bg-fill "${file}";
            # walchange "$file"
            custom_wal.py "$file"
            ;;
        "r")
            convert -rotate 90 "$file" "$file"
            ;;
        "R")
            convert -rotate -90 "$file" "$file"
            ;;
        "d")
         [ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "Deleted" "$file"
            ;;
        # "f")
        #     convert -flop "$file" "$file"
        #     ;;
        # "y")
        #     fullpath=$(readlink -f "$file")
        #     extension="${fullpath##*.}"
        #     [ "$extension" = "jpg" ] && extension=jpeg
        #     xclip -selection clipboard -t "image/$extension" "$fullpath" &&
        #     notify-send "Image data of \`$file\` copied to clipboard" &
        #     ;;
        # "Y")
        #     readlink -f "$file" | tr -d '\n' | xclip -selection clipboard &&
        #     notify-send "\`$(readlink -f "$file")\` copied to clipboard" &
        #     ;;
        "i")
            notify-send "File information" "$(identify "$file")"
            ;;
    esac
done
