#!/bin/sh

while read -r file; do
	case "$1" in
	"w")
		if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
			"$HOME/.config/hypr/scripts/wallpaper.sh" "$file"
		else
			set_wallpaper.sh "$file"
		fi
		;;
	"r")
		convert -rotate 90 "$file" "$file"
		;;
	"R")
		convert -rotate -90 "$file" "$file"
		;;
	"d")
		if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
			[ "$(printf "Yes\\nNo" | wofi -d -i -p "Really delete $file?")" = "Yes" ] && rm "$file"
		else
			[ "$(printf "Yes\\nNo" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file"
		fi
		;;
	"y") # Clipboard, doesn't seem to work with xsel
		printf '%s' "$(basename "$file")" | xclip -selection clipboard &&
			notify-send -t 500 "Clipboard📋" "<b><i>'$file'</i></b> copied" ;;
	"i")
		notify-send "File information" "$(identify "$file")"
		;;
	esac
done
