#!/bin/sh

while read -r file; do
	case "$1" in
	"w")
		set_wallpaper.sh "$file"
		;;
	"r")
		convert -rotate 90 "$file" "$file"
		;;
	"R")
		convert -rotate -90 "$file" "$file"
		;;
	"d")
		[ "$(printf "Yes\\nNo" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "Deleted" "$file"
		;;
	"y") # Clipboard, doesnt seem to work with xsel
		printf '%s' "$(basename "$file")" | xclip -selection clipboard &&
			notify-send -t 500 "Clipboard📋" "<b><i>'$file'</i></b> copied" ;;
	"i")
		notify-send "File information" "$(identify "$file")"
		;;
	esac
done
